CREATE TABLE
    CUSTOMER (
        CID VARCHAR(15) NOT NULL,
        FNAME VARCHAR(30),
        LNAME VARCHAR(30),
        EMAIL VARCHAR(50),
        ADDRESS VARCHAR(50),
        PHONE VARCHAR(15),
        STATUS VARCHAR(30),
        PRIMARY KEY (CID)
    )
CREATE TABLE
    SILVER_AND_ABOVE (
        CID VARCHAR(15) NOT NULL,
        CREDITLINE INT,
        PRIMARY KEY (CID),
        FOREIGN KEY (CID) REFERENCES EMPLOYEE ON DELETE CASCADE ON UPDATE CASCADE
    )
CREATE TABLE
    CREDIT_CARD (
        CCNUMBER VARCHAR(15) NOT NULL,
        SECNUMBER VARCHAR(15),
        OWNERNAME VARCHAR(60),
        CCTYPE VARCHAR(30),
        BILADDRESS VARCHAR(50),
        EXPDATE DATE,
        STOREDCARDCID VARCHAR(15) NOT NULL,
        PRIMARY KEY (CCNUMBER),
        FOREIGN KEY (STOREDCARDCID) REFERENCES CUSTOMER (CID) ON DELETE CASCADE ON UPDATE CASCADE
    )
CREATE TABLE
    SHIPPING_ADDRESS (
        CID VARCHAR(15) NOT NULL,
        SANAME VARCHAR(50) NOT NULL,
        RECIPIENTNAME VARCHAR(50),
        STREET VARCHAR(50),
        SNUMBER INT,
        CITY VARCHAR(30),
        ZIP INTEGER,
        STATE VARCHAR(30),
        COUNTRY VARCHAR(30),
        PRIMARY KEY (CID, SANAME),
        FOREIGN KEY (CID) REFERENCES CUSTOMER ON DELETE CASCADE ON UPDATE CASCADE
    )
CREATE TABLE
    BASKET (
        BID VARCHAR(15) NOT NULL,
        CID VARCHAR(15) NOT NULL,
        PRIMARY KEY (BID),
        FOREIGN KEY (CID) REFERENCES CUSTOMER ON DELETE CASCADE ON UPDATE CASCADE
    )
CREATE TABLE
    TRANSACTION_TABLE (
        BID VARCHAR(15) NOT NULL,
        CCNUMBER VARCHAR(15) NOT NULL,
        CID VARCHAR(15) NOT NULL,
        SANAME VARCHAR(50) NOT NULL,
        TDATE DATE,
        TTAG VARCHAR(30),
        PRIMARY KEY (BID, CCNUMBER, CID, SANAME),
        FOREIGN KEY (BID) REFERENCES BASKET ON DELETE CASCADE ON UPDATE CASCADE,
        FOREIGN KEY (CCNUMBER) REFERENCES CREDIT_CARD ON DELETE CASCADE ON UPDATE CASCADE,
        FOREIGN KEY (CID, SANAME) REFERENCES SHIPPING_ADDRESS ON DELETE CASCADE ON UPDATE CASCADE
    )
CREATE TABLE
    PRODUCT (
        PID VARCHAR(15) NOT NULL,
        PTYPE VARCHAR(30),
        PNAME VARCHAR(30),
        PPRICE DECIMAL,
        DESCRIPTION VARCHAR(200),
        PQUANTITY INTEGER,
        PRIMARY KEY (PID)
    )
CREATE TABLE
    APPEARS_IN (
        BID VARCHAR(15) NOT NULL,
        PID VARCHAR(15) NOT NULL,
        QUANTITY INTEGER,
        PRICESOLD DECIMAL,
        PRIMARY KEY (BID, PID),
        FOREIGN KEY (BID) REFERENCES BASKET ON DELETE CASCADE ON UPDATE CASCADE,
        FOREIGN KEY (PID) REFERENCES PRODUCT ON DELETE CASCADE ON UPDATE CASCADE
    )
CREATE TABLE
    OFFER_PRODUCT (
        PID VARCHAR(15) NOT NULL,
        OFFERPRICE DECIMAL,
        PRIMARY KEY (PID),
        FOREIGN KEY (PID) REFERENCES PRODUCT ON DELETE CASCADE ON UPDATE CASCADE
    )
CREATE TABLE
    COMPUTER (
        PID VARCHAR(15) NOT NULL,
        CPUTYPE VARCHAR(50),
        PRIMARY KEY (PID),
        FOREIGN KEY (PID) REFERENCES PRODUCT ON DELETE CASCADE ON UPDATE CASCADE
    )
CREATE TABLE
    PRINTER (
        PID VARCHAR(15) NOT NULL,
        PRINTERTYPE VARCHAR(50),
        RESOLUTION VARCHAR(50),
        PRIMARY KEY (PID),
        FOREIGN KEY (PID) REFERENCES PRODUCT ON DELETE CASCADE ON UPDATE CASCADE
    )
CREATE TABLE
    LAPTOP (
        PID VARCHAR(15) NOT NULL,
        BTYPE VARCHAR(50),
        WEIGHT VARCHAR(15),
        PRIMARY KEY (PID),
        FOREIGN KEY (PID) REFERENCES PRODUCT ON DELETE CASCADE ON UPDATE CASCADE
    )